function plot_price_entropy(variable)

set(groot, ...
'DefaultFigureColor', 'w', ...
'DefaultAxesLineWidth', 0.5, ...
'DefaultAxesXColor', 'k', ...
'DefaultAxesYColor', 'k', ...
'DefaultAxesFontUnits', 'points', ...
'DefaultAxesFontSize', 10, ...
'DefaultAxesFontName', 'Helvetica', ...
'DefaultLineLineWidth', 2, ...
'DefaultTextFontUnits', 'Points', ...
'DefaultTextFontSize', 10, ...
'DefaultTextFontName', 'Helvetica', ...
'DefaultAxesBox', 'off', ...
'DefaultAxesTickLength', [0.02 0.025]);
set(groot, 'DefaultAxesTickDir', 'out');
set(groot, 'DefaultAxesTickDirMode', 'manual');
rgb=[[1 0 0];[0 0 1];[0, 0.65, 0];[1 0 1];[0, 0.4470, 0.7410];[0.8500, 0.3250, 0.0980];[0.6350, 0.0780, 0.1840];];



%% import data to matlab
datareal=importdata('/Users/Manzanita/Tesis_felix/Tesis/Code/ficheroscsv/datareal.csv',1);
dataSSimulada=importdata('/Users/Manzanita/Tesis_felix/Tesis/Code/ficheroscsv/dataSSimulada.csv',1);

[MDataSimulada]=read_plot_data(dataSSimulada);
[MDataReal]=read_plot_data(datareal);
%% plot data into matlab
figure
hold on
set(gca,'fontsize',15,'LineWidth',2)
plot(datetime(MDataSimulada(:,2)),str2double(MDataSimulada(:,1)),'LineWidth',1.5,'Color',rgb(7,:))
plot(datetime(MDataReal(:,2)),str2double(MDataReal(:,1)),'LineWidth',1.5,'Color',rgb(5,:))
title(['Entropia real y simulada del mercado DJJA ',num2str(k)]);
xl=xlabel('Fechas','FontSize',20);
yl=ylabel('Entropia','FontSize',20);
grid on
hold off

